// Generated by CoffeeScript 1.6.3
'use strict';
var assert;

assert = require('assert');

describe('webapp-aberigle generator', function() {
  return it('can be imported without blowing up', function() {
    var app;
    app = require('../app');
    return assert(app !== void 0);
  });
});
